const perfiles = require('./perfiles');
const nivelesAcademicos = require('./nivelesAcademicos');

module.exports = [
  {
    cedula: '001-1686342-4',
    nombres: 'Anubis',
    apellidos: 'Lockward Botello',
    email: 'anubis.lockward@gmail.com',
    dob: '07/03/1982',
    age: 42,
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 10000,
    perfilCandidato: perfiles[1].text,
    imgUrl: '/res/img/001-1686342-4_user.png',
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Dominican Republic',
      selectedIndex: 62,
      region: 'Puerto Plata',
      latLon: [19.7101367, -70.69167680888046],
    },
    country: 'Dominican Republic',
    region: 'Puerto Plata',
    notas: '',
  },
  {
    cedula: '002-3658742-8',
    nombres: 'Carlos',
    apellidos: 'Martinez Lopez',
    email: 'carlos.martinez@example.com',
    dob: '05/12/1990',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'Tech Solutions Corp',
    exp_salario: 15000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Dominican Republic',
      selectedIndex: 62,
      region: 'Peravia',
      latLon: [18.3309575, -70.3712349],
    },
    country: 'Dominican Republic',
    region: 'Santiago',
    notas: 'Gran capacidad de análisis.',
  },
  {
    cedula: '001-8492736-9',
    nombres: 'Maria',
    apellidos: 'Gomez Hernandez',
    email: 'maria.gomez@example.com',
    dob: '10/08/1987',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 20000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Afghanistan',
      selectedIndex: 0,
      region: 'Kandahar',
      latLon: [31.6205738, 65.7157573],
    },
    country: 'Dominican Republic',
    region: 'Distrito Nacional',
    notas: 'Experiencia en estrategias digitales.',
  },
  {
    cedula: '003-2948753-2',
    nombres: 'Juan',
    apellidos: 'Perez Diaz',
    email: 'juan.perez@example.com',
    dob: '12/25/1985',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 12000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Japan',
      selectedIndex: 109,
      region: 'Ishikawa',
      latLon: [36.9890574, 136.8162839],
    },
    country: 'Dominican Republic',
    region: 'La Vega',
    notas: 'Motivado para iniciar carrera en administración.',
  },
  {
    cedula: '004-9876543-1',
    nombres: 'Luis',
    apellidos: 'Reyes Sanchez',
    email: 'luis.reyes@example.com',
    dob: '09/15/1993',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'WebDev Enterprises',
    exp_salario: 25000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'United States of America',
      selectedIndex: 233,
      region: 'Florida',
      latLon: [27.7567667, -81.4639835],
    },
    country: 'Dominican Republic',
    region: 'San Cristobal',
    notas: 'Fuerte en frameworks frontend.',
  },
  {
    cedula: '005-3769823-7',
    nombres: 'Ana',
    apellidos: 'Rodriguez Pena',
    email: 'ana.rodriguez@example.com',
    dob: '11/02/1995',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 18000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Dominican Republic',
      selectedIndex: 62,
      region: 'Distrito Nacional (Santo Domingo)',
      latLon: [18.4801972, -69.942111],
    },
    country: 'Dominican Republic',
    region: 'La Romana',
    notas: 'Excelente comunicación interpersonal.',
  },
  {
    cedula: '001-5698342-6',
    nombres: 'Maria',
    apellidos: 'Gomez Fernandez',
    email: 'maria.gomez@example.com',
    dob: '09/23/1985',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'TechCorp Solutions',
    exp_salario: 40000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Colombia',
      selectedIndex: 47,
      region: 'Distrito Capital de Bogota',
      latLon: [4.6533816, -74.0836333],
    },
    country: 'Dominican Republic',
    region: 'Santiago',
    notas: 'Experiencia en desarrollo de software embebido.',
  },
  {
    cedula: '001-2987654-3',
    nombres: 'Juan',
    apellidos: 'Perez Rodriguez',
    email: 'juan.perez@example.com',
    dob: '05/12/1992',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 25000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Costa Rica',
      selectedIndex: 52,
      region: 'Limon',
      latLon: [10.099908899999999, -83.34318729447185],
    },
    country: 'Dominican Republic',
    region: 'La Vega',
    notas: 'Creativo especializado en branding.',
  },
  {
    cedula: '001-9871236-9',
    nombres: 'Laura',
    apellidos: 'Diaz Martinez',
    email: 'laura.diaz@example.com',
    dob: '11/02/1989',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'Global Tech Innovators',
    exp_salario: 35000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Dominican Republic',
      selectedIndex: 62,
      region: 'San Juan',
      latLon: [18.87967, -71.2862706],
    },
    country: 'Dominican Republic',
    region: 'San Cristobal',
    notas: 'Especialista en marketing digital.',
  },
  {
    cedula: '001-4568321-8',
    nombres: 'Carlos',
    apellidos: 'Lopez Ruiz',
    email: 'carlos.lopez@example.com',
    dob: '03/15/1994',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 20000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Puerto Rico',
      selectedIndex: 176,
      region: 'Bayamon',
      latLon: [18.3990551, -66.1560326],
    },
    country: 'Dominican Republic',
    region: 'Puerto Plata',
    notas: 'Interesado en desarrollo front-end.',
  },
  {
    cedula: '001-6759341-2',
    nombres: 'Ana',
    apellidos: 'Mendez Castillo',
    email: 'ana.mendez@example.com',
    dob: '08/09/1990',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'Tech Innovations SRL',
    exp_salario: 30000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Dominican Republic',
      selectedIndex: 62,
      region: 'La Vega',
      latLon: [19.0520669, -70.6316324],
    },
    country: 'Dominican Republic',
    region: 'Santo Domingo',
    notas: 'Liderazgo en proyectos administrativos.',
  },
  {
    cedula: '001-1234567-1',
    nombres: 'Pedro',
    apellidos: 'Sanchez Vargas',
    email: 'pedro.sanchez@example.com',
    dob: '02/11/1998',
    candidateExp: 'Sin experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 18000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'United Kingdom of Great Britain and Northern Ireland',
      selectedIndex: 232,
      region: 'England',
      latLon: [52.5310214, -1.2649062],
    },
    country: 'Dominican Republic',
    region: 'Santo Domingo',
    notas: 'Reciente graduado en informática.',
  },
  {
    cedula: '001-7654321-4',
    nombres: 'Camila',
    apellidos: 'Ramirez Paredes',
    email: 'camila.ramirez@example.com',
    dob: '07/19/1987',
    candidateExp: 'Con experiencia',
    currentlyWorking: true,
    job_actual: 'Creative Solutions Inc.',
    exp_salario: 40000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Korea (the Republic of)',
      selectedIndex: 116,
      region: 'Seoul-teukbyeolsi',
      latLon: [37.5358612, 127.0117095],
    },
    country: 'Dominican Republic',
    region: 'Santiago',
    notas: 'Especializada en estrategias de marca.',
  },
  {
    cedula: '001-5432167-9',
    nombres: 'Ricardo',
    apellidos: 'Martinez Gomez',
    email: 'ricardo.martinez@example.com',
    dob: '10/22/1990',
    candidateExp: 'Con experiencia',
    currentlyWorking: false,
    job_actual: '',
    exp_salario: 35000,
    perfilCandidato: perfiles[1].text,
    nivelAcademico: nivelesAcademicos[1].text,
    countryRegionData: {
      country: 'Cuba',
      selectedIndex: 55,
      region: 'Santiago de Cuba',
      latLon: [20.0214637, -75.8294928],
    },
    country: 'Dominican Republic',
    region: 'La Vega',
    notas: 'Experiencia en gestión de proyectos.',
  },
];
