module.exports.countryNames = [
  { code: 'ad', country: 'Andorra' },
  { code: 'ae', country: 'United Arab Emirates' },
  { code: 'af', country: 'Afghanistan' },
  { code: 'ag', country: 'Antigua and Barbuda' },
  { code: 'ai', country: 'Anguilla' },
  { code: 'al', country: 'Albania' },
  { code: 'am', country: 'Armenia' },
  { code: 'ao', country: 'Angola' },
  { code: 'aq', country: 'Antarctica' },
  { code: 'ar', country: 'Argentina' },
  { code: 'as', country: 'American Samoa' },
  { code: 'at', country: 'Austria' },
  { code: 'au', country: 'Australia' },
  { code: 'aw', country: 'Aruba' },
  { code: 'ax', country: 'Åland Islands' },
  { code: 'az', country: 'Azerbaijan' },
  { code: 'ba', country: 'Bosnia and Herzegovina' },
  { code: 'bb', country: 'Barbados' },
  { code: 'bd', country: 'Bangladesh' },
  { code: 'be', country: 'Belgium' },
  { code: 'bf', country: 'Burkina Faso' },
  { code: 'bg', country: 'Bulgaria' },
  { code: 'bh', country: 'Bahrain' },
  { code: 'bi', country: 'Burundi' },
  { code: 'bj', country: 'Benin' },
  { code: 'bl', country: 'Saint Barthélemy' },
  { code: 'bm', country: 'Bermuda' },
  { code: 'bn', country: 'Brunei Darussalam' },
  { code: 'bo', country: 'Bolivia, Plurinational State of' },
  { code: 'br', country: 'Brazil' },
  { code: 'bs', country: 'Bahamas' },
  { code: 'bt', country: 'Bhutan' },
  { code: 'bv', country: 'Bouvet Island' },
  { code: 'bw', country: 'Botswana' },
  { code: 'by', country: 'Belarus' },
  { code: 'bz', country: 'Belize' },
  { code: 'ca', country: 'Canada' },
  { code: 'cc', country: 'Cocos (Keeling) Islands' },
  { code: 'cd', country: 'Congo, the Democratic Republic of the' },
  { code: 'cf', country: 'Central African Republic' },
  { code: 'cg', country: 'Congo' },
  { code: 'ch', country: 'Switzerland' },
  { code: 'ci', country: "Côte d'Ivoire" },
  { code: 'ck', country: 'Cook Islands' },
  { code: 'cl', country: 'Chile' },
  { code: 'cm', country: 'Cameroon' },
  { code: 'cn', country: 'China' },
  { code: 'co', country: 'Colombia' },
  { code: 'cr', country: 'Costa Rica' },
  { code: 'cu', country: 'Cuba' },
  { code: 'cv', country: 'Cabo Verde' },
  { code: 'cw', country: 'Curaçao' },
  { code: 'cx', country: 'Christmas Island' },
  { code: 'cy', country: 'Cyprus' },
  { code: 'cz', country: 'Czechia' },
  { code: 'de', country: 'Germany' },
  { code: 'dj', country: 'Djibouti' },
  { code: 'dk', country: 'Denmark' },
  { code: 'dm', country: 'Dominica' },
  { code: 'do', country: 'Dominican Republic' },
  { code: 'dz', country: 'Algeria' },
  { code: 'ec', country: 'Ecuador' },
  { code: 'ee', country: 'Estonia' },
  { code: 'eg', country: 'Egypt' },
  { code: 'eh', country: 'Western Sahara' },
  { code: 'er', country: 'Eritrea' },
  { code: 'es', country: 'Spain' },
  { code: 'et', country: 'Ethiopia' },
  { code: 'fi', country: 'Finland' },
  { code: 'fj', country: 'Fiji' },
  { code: 'fk', country: 'Falkland Islands (Malvinas)' },
  { code: 'fm', country: 'Micronesia, Federated States of' },
  { code: 'fo', country: 'Faroe Islands' },
  { code: 'fr', country: 'France' },
  { code: 'ga', country: 'Gabon' },
  {
    code: 'gb',
    country: 'United Kingdom of Great Britain and Northern Ireland',
  },
  { code: 'gd', country: 'Grenada' },
  { code: 'ge', country: 'Georgia' },
  { code: 'gf', country: 'French Guiana' },
  { code: 'gg', country: 'Guernsey' },
  { code: 'gh', country: 'Ghana' },
  { code: 'gi', country: 'Gibralta' },
  { code: 'gl', country: 'Greenland' },
  { code: 'gm', country: 'Gambia' },
  { code: 'gn', country: 'Guinea' },
  { code: 'gp', country: 'Guadeloupe' },
  { code: 'gq', country: 'Equatorial Guinea' },
  { code: 'gr', country: 'Greece' },
  { code: 'gs', country: 'South Georgia and the South Sandwich Islands' },
  { code: 'gt', country: 'Guatemala' },
  { code: 'gu', country: 'Guam' },
  { code: 'gw', country: 'Guinea-Bissau' },
  { code: 'gy', country: 'Guyana' },
  { code: 'hk', country: 'Hong Kong' },
  { code: 'hm', country: 'Heard Island and McDonald Islands' },
  { code: 'hn', country: 'Honduras' },
  { code: 'hr', country: 'Croatia' },
  { code: 'ht', country: 'Haiti' },
  { code: 'hu', country: 'Hungary' },
  { code: 'id', country: 'Indonesia' },
  { code: 'ie', country: 'Ireland' },
  { code: 'il', country: 'Israel' },
  { code: 'im', country: 'Isle of Man' },
  { code: 'in', country: 'India' },
  { code: 'io', country: 'British Indian Ocean Territory' },
  { code: 'iq', country: 'Iraq' },
  { code: 'ir', country: 'Iran, Islamic Republic of' },
  { code: 'is', country: 'Iceland' },
  { code: 'it', country: 'Italy' },
  { code: 'je', country: 'Jersey' },
  { code: 'jm', country: 'Jamaica' },
  { code: 'jo', country: 'Jordan' },
  { code: 'jp', country: 'Japan' },
  { code: 'ke', country: 'Kenya' },
  { code: 'kg', country: 'Kyrgyzstan' },
  { code: 'kh', country: 'Cambodia' },
  { code: 'ki', country: 'Kiribati' },
  { code: 'km', country: 'Comoros' },
  { code: 'kn', country: 'Saint Kitts and Nevis' },
  { code: 'kp', country: "Korea, Democratic People's Republic of" },
  { code: 'kr', country: 'Korea, Republic of' },
  { code: 'kw', country: 'Kuwait' },
  { code: 'ky', country: 'Cayman Islands' },
  { code: 'kz', country: 'Kazakhstan' },
  { code: 'la', country: "Lao People's Democratic Republic" },
  { code: 'lb', country: 'Lebanon' },
  { code: 'lc', country: 'Saint Lucia' },
  { code: 'li', country: 'Liechtenstein' },
  { code: 'lk', country: 'Sri Lanka' },
  { code: 'lr', country: 'Liberia' },
  { code: 'ls', country: 'Lesotho' },
  { code: 'lt', country: 'Lithuania' },
  { code: 'lu', country: 'Luxembourg' },
  { code: 'lv', country: 'Latvia' },
  { code: 'ly', country: 'Libya' },
  { code: 'ma', country: 'Morocco' },
  { code: 'mc', country: 'Monaco' },
  { code: 'md', country: 'Moldova, Republic of' },
  { code: 'me', country: 'Montenegro' },
  { code: 'mf', country: 'Collectivity of Saint Martin' },
  { code: 'mg', country: 'Madagascar' },
  { code: 'mh', country: 'Marshall Islands' },
  { code: 'mk', country: 'Macedonia, the former Yugoslav Republic of' },
  { code: 'ml', country: 'Mali' },
  { code: 'mm', country: 'Myanmar' },
  { code: 'mn', country: 'Mongolia' },
  { code: 'mo', country: 'Macao' },
  { code: 'mp', country: 'Northern Mariana Islands' },
  { code: 'mq', country: 'Martinique' },
  { code: 'mr', country: 'Mauritania' },
  { code: 'ms', country: 'Montserrat' },
  { code: 'mt', country: 'Malta' },
  { code: 'mu', country: 'Mauritius' },
  { code: 'mv', country: 'Maldives' },
  { code: 'mw', country: 'Malawi' },
  { code: 'mx', country: 'Mexico' },
  { code: 'my', country: 'Malaysia' },
  { code: 'mz', country: 'Mozambique' },
  { code: 'na', country: 'Namibia' },
  { code: 'nc', country: 'New Caledonia' },
  { code: 'ne', country: 'Niger' },
  { code: 'nf', country: 'Norfolk Island' },
  { code: 'ng', country: 'Nigeria' },
  { code: 'ni', country: 'Nicaragua' },
  { code: 'nl', country: 'Netherlands' },
  { code: 'no', country: 'Norway' },
  { code: 'np', country: 'Nepal' },
  { code: 'nr', country: 'Nauru' },
  { code: 'nu', country: 'Niue' },
  { code: 'nz', country: 'New Zealand' },
  { code: 'om', country: 'Oman' },
  { code: 'pa', country: 'Panama' },
  { code: 'pe', country: 'Peru' },
  { code: 'pf', country: 'French Polynesia' },
  { code: 'pg', country: 'Papua New Guinea' },
  { code: 'ph', country: 'Philippines' },
  { code: 'pk', country: 'Pakistan' },
  { code: 'pl', country: 'Poland' },
  { code: 'pm', country: 'Saint Pierre and Miquelon' },
  { code: 'pn', country: 'Pitcairn' },
  { code: 'pr', country: 'Puerto Rico' },
  { code: 'ps', country: 'Palestine, State of' },
  { code: 'pt', country: 'Portugal' },
  { code: 'pw', country: 'Palau' },
  { code: 'py', country: 'Paraguay' },
  { code: 'qa', country: 'Qatar' },
  { code: 're', country: 'Réunion' },
  { code: 'ro', country: 'Romania' },
  { code: 'rs', country: 'Serbia' },
  { code: 'ru', country: 'Russian Federation' },
  { code: 'rw', country: 'Rwanda' },
  { code: 'sa', country: 'Saudi Arabia' },
  { code: 'sb', country: 'Solomon Islands' },
  { code: 'sc', country: 'Seychelles' },
  { code: 'sd', country: 'Sudan' },
  { code: 'se', country: 'Sweden' },
  { code: 'sg', country: 'Singapore' },
  { code: 'sh', country: 'Saint Helena, Ascension and Tristan da Cunha' },
  { code: 'si', country: 'Slovenia' },
  { code: 'sk', country: 'Slovakia' },
  { code: 'sl', country: 'Sierra Leone' },
  { code: 'sm', country: 'San Marino' },
  { code: 'sn', country: 'Senegal' },
  { code: 'so', country: 'Somalia' },
  { code: 'sr', country: 'Suriname' },
  { code: 'ss', country: 'South Sudan' },
  { code: 'st', country: 'Sao Tome and Principe' },
  { code: 'sv', country: 'El Salvador' },
  { code: 'sx', country: 'Sint Maarten' },
  { code: 'sy', country: 'Syrian Arab Republic' },
  { code: 'sz', country: 'Swaziland' },
  { code: 'tc', country: 'Turks and Caicos Islands' },
  { code: 'td', country: 'Chad' },
  { code: 'tf', country: 'French Southern Territories' },
  { code: 'tg', country: 'Togo' },
  { code: 'th', country: 'Thailand' },
  { code: 'tj', country: 'Tajikistan' },
  { code: 'tk', country: 'Tokelau' },
  { code: 'tl', country: 'Timor-Leste' },
  { code: 'tm', country: 'Turkmenistan' },
  { code: 'tn', country: 'Tunisia' },
  { code: 'to', country: 'Tonga' },
  { code: 'tr', country: 'Turkey' },
  { code: 'tt', country: 'Trinidad and Tobago' },
  { code: 'tv', country: 'Tuvalu' },
  { code: 'tw', country: 'Taiwan, Province of China' },
  { code: 'tz', country: 'Tanzania, United Republic of' },
  { code: 'ua', country: 'Ukraine' },
  { code: 'ug', country: 'Uganda' },
  { code: 'um', country: 'United States Minor Outlying Islands' },
  { code: 'us', country: 'United States of America' },
  { code: 'uy', country: 'Uruguay' },
  { code: 'uz', country: 'Uzbekistan' },
  { code: 'va', country: 'Holy See' },
  { code: 'vc', country: 'Saint Vincent and the Grenadines' },
  { code: 've', country: 'Venezuela, Bolivarian Republic of' },
  { code: 'vg', country: 'Virgin Islands, British' },
  { code: 'vi', country: 'Virgin Islands, U.S.' },
  { code: 'vn', country: 'Vietnam' },
  { code: 'vu', country: 'Vanuatu' },
  { code: 'wf', country: 'Wallis and Futuna' },
  { code: 'ws', country: 'Samoa' },
  { code: 'ye', country: 'Yemen' },
  { code: 'yt', country: 'Mayotte' },
  { code: 'za', country: 'South Africa' },
  { code: 'zm', country: 'Zambia' },
  { code: 'zw', country: 'Zimbabwe' },
];
